# Generated by Django 2.2.2 on 2019-06-27 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Main',
            new_name='MainBanner',
        ),
    ]
