# Generated by Django 2.2.2 on 2019-06-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20190627_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_banner_1', models.ImageField(upload_to='brand_banner_1')),
                ('brand_banner_2', models.ImageField(upload_to='brand_banner_2')),
            ],
        ),
        migrations.CreateModel(
            name='BrandImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ImageField(upload_to='main_brand')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ImageField(upload_to='menu')),
            ],
        ),
        migrations.RenameField(
            model_name='mainbanner',
            old_name='image',
            new_name='main',
        ),
    ]
